config/routes.rb
Rails.application.routes.draw do
  resources :blog_reviews
  get 'users/show'
  root 'static_pages#home'
  get 'static_pages/home'
  devise_for :users
  resources :blogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_one_attached :image
    has_many :blog_review, -> { order "created_at DESC"}
end

app/models/blog_review.rb
class BlogReview < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :avatar
    validates :name, presence: true
  validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
     devise_parameter_sanitizer.permit :sign_up, keys: [:name, :age,:avatar]
     devise_parameter_sanitizer.permit :account_update, keys: [:name, :age,:avatar]
    end    
end 

app/controllers/blog_reviews_controller.rb
class BlogReviewsController < ApplicationController
  before_action :set_blog_review, only: %i[ show edit update destroy ]

  # GET /blog_reviews or /blog_reviews.json
  def index
    @blog_reviews = BlogReview.all
  end

  # GET /blog_reviews/1 or /blog_reviews/1.json
  def show
  end

  # GET /blog_reviews/new
  def new
    @blog_review = BlogReview.new
  end

  # GET /blog_reviews/1/edit
  def edit
  end

  # POST /blog_reviews or /blog_reviews.json
  def create
    @blog_review = BlogReview.new(blog_review_params)
    @blog_review.user_id = current_user.id
    respond_to do |format|
      if @blog_review.save
        url = "/blogs/" + @blog_review.blog_id.to_s
        format.html { redirect_to url, notice: 'Blog comment was successfully created.' }
        format.json { render :show, status: :created, location: @blog_review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_reviews/1 or /blog_reviews/1.json
  def update
    respond_to do |format|
      if @blog_review.update(blog_review_params)
        format.html { redirect_to @blog_review, notice: "Blog review was successfully updated." }
        format.json { render :show, status: :ok, location: @blog_review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_reviews/1 or /blog_reviews/1.json
  def destroy
    @blog_review.destroy
    respond_to do |format|
      format.html { redirect_to blog_reviews_url, notice: "Blog review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_review
      @blog_review = BlogReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_review_params
      params.require(:blog_review).permit(:user_id, :blog_id, :review)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
      @blog_review = BlogReview.new
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :description,:image,:description2)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_reviews_helper.rb
module BlogReviewsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_reviews/_form.html.erb
<%= form_with(model: blog_review, local: true) do |form| %>
  <% if blog_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_review.errors.count, "error") %> prohibited this blog_review from being saved:</h2>

      <ul>
        <% blog_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :blog_id %>
    <%= form.number_field :blog_id %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_reviews/edit.html.erb
<h1>Editing Blog Review</h1>

<%= render 'form', blog_review: @blog_review %>

<%= link_to 'Show', @blog_review %> |
<%= link_to 'Back', blog_reviews_path %>

app/views/blog_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Blog</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_reviews.each do |blog_review| %>
      <tr>
        <td><%= blog_review.user_id %></td>
        <td><%= blog_review.blog_id %></td>
        <td><%= blog_review.review %></td>
        <td><%= link_to 'Show', blog_review %></td>
        <td><%= link_to 'Edit', edit_blog_review_path(blog_review) %></td>
        <td><%= link_to 'Destroy', blog_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog Review', new_blog_review_path %>

app/views/blog_reviews/new.html.erb
<h1>New Blog Review</h1>

<%= render 'form', blog_review: @blog_review %>

<%= link_to 'Back', blog_reviews_path %>

app/views/blog_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @blog_review.user_id %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @blog_review.blog_id %>
</p>

<p>
  <strong>Review:</strong>
  <%= @blog_review.review %>
</p>

<%= link_to 'Edit', edit_blog_review_path(@blog_review) %> |
<%= link_to 'Back', blog_reviews_path %>

app/views/blogs/_form.html.erb
<div class="form-blogs">
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title%>
    <%= form.text_field :title, class:"input-data-form" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class:"input-data-form" %>
  </div>
  <div class="field">
    <%= form.label :description2, 'Message' %>
    <%= form.text_area :description2, class:"input-data-form" %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %><br>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/blogs/edit.html.erb
<div class="common-form">
    <h1 class="title">Editing Blog</h1>

    <%= render 'form', blog: @blog %>

    <%= link_to 'Show', @blog %> |
    <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">My Blogs</h1>


<div class="btn-add-blogs">
    <%= link_to '<i class="fa fa-plus-circle" aria-hidden="true"></i> New Blog'.html_safe, new_blog_path %>
</div>
<div class="list-blogs">
  <div class="row">
  <%if @blogs.length > 0 %>
    <% @blogs.each do |blog| %>
      <div class="col-md-4">
            <div class="card">
                <% if blog.image.attached? %>
              <%= image_tag blog.image %>
                 <% end %>
             <div class="card-body">
              <h5 class="card-title"> <%= blog.title %></h5>
              <p class="card-text">Description : <%= blog.description%></p>
              <p class="card-text">Details : <%= blog.description2 %></p>
              <div class="read-more">
                  <%= link_to 'Learn more', blog %>
              </div>

              <ul class="nav nav-pills actions-blog">
                <li role="presentation"><%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_blog_path(blog) %></li>
                <li role="presentation"><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, blog, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
            </div>
          </div>
      </div>
      
    <% end %>

  <%else%>
      <h3 class="text-center">No Blogs? Please create your own blogs....</h3>

  <% end %>
  </div>

</div>

app/views/blogs/new.html.erb
<div class="common-form">
    <h1 class="title">New Blog</h1>

    <%= render 'form', blog: @blog %>

    <%= link_to 'Back', blogs_path %>
<div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>



<div class="blogs-details">

    <h1 class="title">Blog Details</h1>
    <div class="details">
        <div class="row">
            <div class="col-md-5">
                <% if @blog.image.attached? %>
                  <%= image_tag @blog.image %>
                <% end %>
            </div>
            <div class="col-md-7">
              <h3 class="title">Blogs About <%= @blog.title %></h3>
              <p>Description : <%= @blog.description %></p>
              <p>Details</p>
              <span> <%= @blog.description2 %></span>
            </div>

        </div>
    </div>

    <div class="review-form">
      <h3 class="title">Comment about blogs</h3>
      <div class="comment">
      <%= form_with(model: @blog_review, local: true) do |form| %>
        <div class= "field">
          <%= form.text_area :review, placeholder:"Enter input your comment....", class:"comment-form" %>
          <%= form.hidden_field :blog_id, :value => @blog.id %>
        </div>
        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>

      </div>
      <div class="list-comments">
      <h3 class="title">List Comment</h3>
      <ul class="nav nav-pills nav-stacked">
      <% @blog.blog_review.each do |blog_review|%>
        <li role="presentation"><a href="#">User: <i><%= blog_review.user.name%></i></a></li></li>
        <li role="presentation"><a href="#"><%= blog_review.review %></a></li></li>
    <% end %>
    </ul>
      </div>


    </div>

</div>



<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>Group1</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
   </head>
   <body>
      <div class="header">
         <ul class="nav nav-pills">
            <li class="nav-item">
               <%= link_to "Home", root_path, class:"nav-link" %>
            </li>
            <% if user_signed_in? %>
               <li class="nav-item">
                  <%= link_to "BLogs", blogs_path %>
                </li>
               <li class="nav-item">
                  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
               </li>

              
            <% else %>
            <li class="nav-item">
               <%= link_to "sign in", new_user_session_path %>
            </li>
            <li class="nav-item">
               <%= link_to "sign up", new_user_registration_path %>
            </li>
            <% end %>
         </ul>

      </div>
      <div class="container">
      <% if user_signed_in? %>
            <h3 class="text-center">Hello、<%= link_to current_user.name, users_show_path %></h3>
      <%end%>
         <%= yield %>
      </div>
   </body>
</html>

app/views/static_pages/home.html.erb
<h1 class="title">HOME PAGE</h1>
<%= link_to "Blogs List", blogs_path %> 

app/views/users/show.html.erb
<div class="profile">

    <h1 class="title">Profile</h1>

    <div class="row">
      <div class="col-md-5">
          <% if @user.avatar.attached? %>
            <%= image_tag @user.avatar %>
          <% end %>
      </div>

      <div class="col-md-7">
        <h3 class="text-center mb-5 mt-5">Information Account </h3>
                    
                
        <table class="table">
          <tbody>
            
              <tr>
                <td>名前 </td>
                <td> : </td>
                <td><%= @user.name%></td>
              </tr>
              <tr>
                <td>メールアドレス </td>
                <td> : </td>
                <td><%= @user.email %></td>
              </tr>
              <tr>
                <td>年齢 </td>
                <td> : </td>
                <td><%= @user.age %></td>
              </tr>
              
          </tbody>
        </table>
      </div>
    </div>
</div>